<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-2SJV0LG" failures="1" tests="5" name="GraphQL" time="138.494" errors="0" timestamp="2023-01-10T13:02:32 IST">
  <testcase classname="testcases.ConnectorsTest" name="connectionTestApi" time="2.826"/>
  <testcase classname="testcases.ConnectorsTest" name="connectionSaveApi" time="23.21">
    <skipped/>
  </testcase> <!-- connectionSaveApi -->
  <testcase classname="testcases.ConnectorsTest" name="connectionSaveApi" time="22.878">
    <skipped/>
  </testcase> <!-- connectionSaveApi -->
  <testcase classname="testcases.ConnectorsTest" name="connectionSaveApi" time="22.798">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
at testcases.ConnectorsTest.connectionSaveApi(ConnectorsTest.java:205)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- connectionSaveApi -->
  <testcase classname="testcases.ConnectorsTest" name="connectionAddApi" time="0.0">
    <skipped/>
  </testcase> <!-- connectionAddApi -->
  <testcase classname="testcases.ConnectorsTest" name="saveConnection" time="0.0">
    <ignored/>
  </testcase> <!-- saveConnection -->
  <testcase classname="testcases.ConnectorsTest" name="addQuery" time="0.0">
    <ignored/>
  </testcase> <!-- addQuery -->
  <testcase classname="testcases.ConnectorsTest" name="connectionTest" time="0.0">
    <ignored/>
  </testcase> <!-- connectionTest -->
</testsuite> <!-- GraphQL -->
